Refactor the init scripts to be more uniform

diff --git a/jobs/haproxy/templates/haproxy_ctl b/jobs/haproxy/templates/haproxy_ctl
--- a/jobs/haproxy/templates/haproxy_ctl
+++ b/jobs/haproxy/templates/haproxy_ctl
@@ -1,72 +1,46 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
-
 set -e
 
-source /var/vcap/jobs/haproxy/helpers/ctl_setup.sh 'haproxy'
-PATH=/var/vcap/packages/haproxy/bin:$PATH
-export PATH=$PATH:/var/vcap/packges/ttar/bin
+source /var/vcap/jobs/haproxy/helpers/ctl_setup.sh haproxy
 
 NAME=haproxy
 DAEMON=$(which haproxy)
 CONFIG=/var/vcap/jobs/haproxy/config/haproxy.config
 DESC="HAProxy"
 USER=vcap
-
-PID_FILE=/var/vcap/sys/run/haproxy/pid
-
-TIMESTAMP=$(which date)
+RUNCMD="${DAEMON} -f ${CONFIG} -D -p ${PID_FILE}"
 
 test -x "${DAEMON}"
 test -f "${CONFIG}"
 
 RETVAL=0
 
-ensure_dir() {
-    DIR=$1
-    if [ ! -d "${DIR}" ] ; then
-        mkdir -p "${DIR}"
-        chown -R "${USER}":"${USER}" "${DIR}"
-        chmod 755 "${DIR}"
-    fi
-}
-
-ensure_dirs() {
-    ensure_dir "$(dirname "${PID_FILE}")"
-}
-
-remove_pid() {
-    rm -f "${PID_FILE}"
-    rmdir "$(dirname "${PID_FILE}")" || :
-}
-
-inflate_certs() {
-	# reconstitute certs based on ttar file
-	mkdir -p ${JOB_DIR}/config/ssl
-	ttar < ${JOB_DIR}/config/certs.ttar
-}
+# exec >>${LOG_DIR}/$NAME.log 2>&1
 
 start_haproxy() {
     status_haproxy
     if [ "${RETVAL}" = 0 ]; then
-        echo "HAProxy is currently running"
+        echo "$DESC is currently running"
     else
         RETVAL=0
         ensure_dirs
         inflate_certs
-        echo "$("${TIMESTAMP}"): Starting HAProxy"
+        echo "$("${TIMESTAMP}"): Starting $DESC"
         set +e
-        "${DAEMON}" -f "${CONFIG}" -D -p "${PID_FILE}" 0<&-
+        # -- Add additional scripts here
+        # --
+        $RUNCMD 0<&-
         RETVAL=$?
         set -e
         case "${RETVAL}" in
             0)
-                echo "$("${TIMESTAMP}"): Finished starting HAProxy"
+                echo "$("${TIMESTAMP}"): Finished starting $DESC"
                 echo "SUCCESS"
                 ;;
             *)
-                echo "$("${TIMESTAMP}"): Errored starting HAProxy"
-                echo "$("${TIMESTAMP}"): Errored starting HAProxy" >&2
+                echo "$("${TIMESTAMP}"): Errored starting $DESC"
+                echo "$("${TIMESTAMP}"): Errored starting $DESC" >&2
                 remove_pid
                 echo "FAILED - check logs"
                 RETVAL=1
@@ -89,7 +63,7 @@ stop_haproxy() {
             echo "FAILED - check logs"
         fi
     else
-        echo "HAProxy not running"
+        echo "$DESC not running"
     fi
 }
 
diff --git a/jobs/keepalived/templates/keepalived_ctl b/jobs/keepalived/templates/keepalived_ctl
--- a/jobs/keepalived/templates/keepalived_ctl
+++ b/jobs/keepalived/templates/keepalived_ctl
@@ -1,108 +1,125 @@
-#!/bin/bash
-APP_DIR=/var/vcap/jobs/keepalived
-PKG_DIR=/var/vcap/packages/keepalived
-BIN_DIR=${PKG_DIR}/bin
-SBIN_DIR=${PKG_DIR}/sbin
-CONF_DIR=${APP_DIR}/config
-RUN_DIR=/var/vcap/sys/run/keepalived
-LOG_DIR=/var/vcap/sys/log/keepalived
+#!/usr/bin/env bash
+#
+set -e
 
-interface_for_ip() {
-    local ip=$1
-    local network=""
+source /var/vcap/jobs/keepalived/helpers/ctl_setup.sh keepalived
+export PATH=$PATH:/var/vcap/packges/ttar/bin
 
-    for route in $(ip route show scope link | cut -d " " -f1); do
-        if [[ $(ip_in_network $route $ip) == 0 ]]; then
-            network=$route
-            break
-        fi
-    done
-
-    if [[ -z $network ]]; then
-        echo "Could not determine an interface for requested VIP: $ip"
-        exit 1
-    fi
-
-    interface=$(ip route show scope link | grep "${network}" | cut -d " " -f3)
-    if [[ -z ${interface} ]]; then
-        echo "Could not find the previously found network ${network} in the routing tables. Something is very wrong"
-        exit 1
-    fi
-    echo "${interface}"
-}
-
-binary_ip() {
-    string_ip=$1
-    i=1
-    binary_ip=0
-    for octet in $(echo "$string_ip" | tr -s "." " "); do
-        binary_ip=$(($binary_ip + ($octet<<(32-(8*$i)))))
-        i=$(($i+1))
-    done
-    echo ${binary_ip}
-}
-
-binary_mask() {
-    bits=$1
-    full_mask=$(((2**32)-1))
-    mask=$((((2**32)-1)-((2**(32-$bits))-1)))
-    echo $mask
-}
-
-ip_in_network() {
-    network=$1
-    target_ip=$2
-
-    net_ip=$(echo $network | cut -d "/" -f1)
-    net_mask=$(echo $network | cut -d "/" -f2)
-
-    net_ip_binary=$(binary_ip "$net_ip")
-    target_ip_binary=$(binary_ip "$target_ip")
-    net_mask_binary=$(binary_mask "$net_mask")
-
-    if [[ $(($net_ip_binary&$net_mask_binary)) == $(($target_ip_binary&$net_mask_binary)) ]]; then
-        echo 0
-    else
-        echo 1
-    fi
-}
-
-exec >>${LOG_DIR}/keepalived.log 2>&1
-
-case $1 in
-
-  start)
-    echo "Starting keepalived... ($(date))"
-    mkdir -p $RUN_DIR $LOG_DIR
-    chown -R vcap:vcap $RUN_DIR $LOG_DIR
-
-    interface=$(interface_for_ip <%= p("keepalived.vip") %>)
-    if [[ $? != 0 || -z ${interface} ]]; then
-        echo "Could not autodetect interface to use for <%= p("keepalived.vip") %>. Cannot continue."
-        exit 1
-    fi
-    if grep "interface auto" ${CONF_DIR}/keepalived.config.template > /dev/null; then
-        sed "s/interface auto/interface ${interface}/" ${CONF_DIR}/keepalived.config.template > ${CONF_DIR}/keepalived.config
-    fi
-
-    $SBIN_DIR/keepalived -l -D -n \
+NAME=keepalived
+DAEMON=$(which keepalived)
+CONFIG=/var/vcap/jobs/keepalived/config/keepalived.config
+DESC="keepalived"
+USER=vcap
+RUNCMD="$DAEMON -l -D \
         -f $CONF_DIR/keepalived.config \
         --pid=$RUN_DIR/keepalived.pid \
         --vrrp_pid=${RUN_DIR}/vrrp.pid \
-        --checkers_pid=${RUN_DIR}/vrrp.pid \
-        >> ${LOG_DIR}/keepalived.log 2>&1 &
-    ;;
+        --checkers_pid=${RUN_DIR}/vrrp.pid"
 
-  stop)
-    echo "Stopping keepalived... ($(date))"
-    for PIDFILE in ${RUN_DIR}/*.pid; do
-        kill -9 -$(cat $PIDFILE)
-        rm -f $PIDFILE
-    done
+test -x "${DAEMON}"
+test -f "${CONFIG}"
 
-    ;;
+RETVAL=0
 
-  *)
-    echo "Usage: keepalived_ctl {start|stop}" ;;
+# exec >>${LOG_DIR}/$NAME.log 2>&1
 
+start_daemon() {
+    status_daemon
+    if [ "${RETVAL}" = 0 ]; then
+        echo "$DESC is currently running"
+    else
+        RETVAL=0
+        ensure_dirs
+        # inflate_certs
+        echo "$("${TIMESTAMP}"): Starting $DESC"
+        set +e
+        # -- Add additional scripts here
+        keepalived_vip_interface
+        keepalived_configure_interface
+        # --
+        $RUNCMD 0<&-
+        RETVAL=$?
+        set -e
+        case "${RETVAL}" in
+            0)
+                echo "$("${TIMESTAMP}"): Finished starting $DESC"
+                echo "SUCCESS"
+                ;;
+            *)
+                echo "$("${TIMESTAMP}"): Errored starting $DESC"
+                echo "$("${TIMESTAMP}"): Errored starting $DESC" >&2
+                remove_pid
+                echo "FAILED - check logs"
+                RETVAL=1
+                ;;
+        esac
+    fi
+}
+
+stop_daemon() {
+    status_daemon
+    if [ "${RETVAL}" = 0 ]; then
+        set +e
+        for pid in $(cat "${PID_FILE}"); do
+            kill ${pid} || RETVAL=$?
+        done
+        set -e
+        if [ "${RETVAL}" = 0 ]; then
+            remove_pid
+        else
+            echo "FAILED - check logs"
+        fi
+    else
+        echo "$DESC not running"
+    fi
+}
+
+# RETVAL = 0 if running, != 0 if stopped
+status_daemon() {
+    if [ -f "${PID_FILE}" ]; then
+        RETVAL=0
+        set +e
+        for pid in $(cat "${PID_FILE}"); do
+            kill -0 "${pid}" > /dev/null 2>&1 || RETVAL=3
+        done
+        kill -0 $(cat "${PID_FILE}") > /dev/null 2>&1
+        if [ $? != 0 ]; then
+            RETVAL=3
+        fi
+        set -e
+    else
+        RETVAL=1
+    fi
+}
+
+restart_daemon() {
+    stop_daemon
+    start_daemon
+}
+
+case "$1" in
+    start)
+        echo -n "Starting ${DESC}: "
+        start_daemon
+        echo "${NAME}."
+        ;;
+    stop)
+        echo -n "Stopping ${DESC}: "
+        stop_daemon
+        echo "${NAME}."
+        ;;
+    status)
+        status_daemon
+        ;;
+    force-reload|reload|restart)
+        echo -n "Restarting ${DESC}: "
+        restart_daemon
+        echo "${NAME}."
+        ;;
+    *)
+        echo "Usage: $0 {start|stop|restart|reload|force-reload}" >&2
+        RETVAL=1
+        ;;
 esac
+
+exit "${RETVAL}"
